version: '2'

services:
  web:
    image: nginx:1.12
    ports:
      - "8081:80"
    volumes:
      - ./monsite:/var/www/monsite
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    links: 
      - php  
  php:
    image: php:7.1-fpm
    volumes:
      - ./monsite:/var/www/monsite
